apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-pod1
  name: test-pod1
  namespace: quota-test
spec:
  containers:
  - image: nginx
    name: my-pod
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
